/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/components/example.component';
const styles_ExampleComponent:any[] = ([] as any[]);
export const RenderType_ExampleComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ExampleComponent,data:{}});
export function View_ExampleComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'pre',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['','\n']))],(null as any),(_ck,_v) => {
    var _co:i1.ExampleComponent = _v.component;
    const currVal_0:any = _co.content;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_ExampleComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'example',([] as any[]),
      (null as any),(null as any),(null as any),View_ExampleComponent_0,RenderType_ExampleComponent)),
      i0.ɵdid(704512,(null as any),0,i1.ExampleComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ExampleComponentNgFactory:i0.ComponentFactory<i1.ExampleComponent> = i0.ɵccf('example',
    i1.ExampleComponent,View_ExampleComponent_Host_0,{type:'type',bind:'bind',clude:'clude',
        definitions:'definitions'},{content:'content'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvZXhhbXBsZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvZXhhbXBsZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9BZG1pbmlzdHJhdG9yL0RvY3VtZW50cy9Qcm9qZWN0cy9BcGlFeHBsb3Jlci9zcmMvQGxpeWFuamllLmFwaWV4cGxvcmVyLXVpL3NyYy9hcHAvY29tcG9uZW50cy9leGFtcGxlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvZXhhbXBsZS5jb21wb25lbnQudHMuRXhhbXBsZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwcmU+XHJcbnt7Y29udGVudH19XHJcbjwvcHJlPiIsIjxleGFtcGxlPjwvZXhhbXBsZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFLO2FBQUE7O0lBQUE7SUFBQTs7OztvQkNBTDtNQUFBO2FBQUE7VUFBQTs7OzsifQ==
