/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './info.component';
import * as i2 from '@angular/platform-browser';
const styles_InfoComponent:any[] = ([] as any[]);
export const RenderType_InfoComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_InfoComponent,data:{}});
export function View_InfoComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'h4',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'b',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['',''])),(_l()(),i0.ɵted((null as any),['   ',''])),(_l()(),i0.ɵted((null as any),
      ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['',''])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),
      (_ck,_v) => {
        var _co:i1.InfoComponent = _v.component;
        const currVal_0:any = ((_co.info == null)? (null as any): _co.info.title);
        _ck(_v,2,0,currVal_0);
        const currVal_1:any = ((_co.info == null)? (null as any): _co.info.version);
        _ck(_v,3,0,currVal_1);
        const currVal_2:any = ((_co.info == null)? (null as any): _co.info.description);
        _ck(_v,6,0,currVal_2);
      });
}
export function View_InfoComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'info',([] as any[]),
      (null as any),(null as any),(null as any),View_InfoComponent_0,RenderType_InfoComponent)),
      i0.ɵdid(573440,(null as any),0,i1.InfoComponent,[i2.Title],(null as any),(null as any))],
      (null as any),(null as any));
}
export const InfoComponentNgFactory:i0.ComponentFactory<i1.InfoComponent> = i0.ɵccf('info',
    i1.InfoComponent,View_InfoComponent_Host_0,{info:'info'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvaW5mby5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvaW5mby5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9BZG1pbmlzdHJhdG9yL0RvY3VtZW50cy9Qcm9qZWN0cy9BcGlFeHBsb3Jlci9zcmMvQGxpeWFuamllLmFwaWV4cGxvcmVyLXVpL3NyYy9hcHAvY29tcG9uZW50cy9pbmZvLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvUHJvamVjdHMvQXBpRXhwbG9yZXIvc3JjL0BsaXlhbmppZS5hcGlleHBsb3Jlci11aS9zcmMvYXBwL2NvbXBvbmVudHMvaW5mby5jb21wb25lbnQudHMuSW5mb0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoND48Yj57e2luZm8/LnRpdGxlfX08L2I+ICZuYnNwOyB7e2luZm8/LnZlcnNpb259fTwvaDQ+XHJcbjxkaXY+e3tpbmZvPy5kZXNjcmlwdGlvbn19PC9kaXY+XHJcbiIsIjxpbmZvPjwvaW5mbz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBO1VBQUEsNENBQUc7TUFBQSxVQUFtQiwyQ0FBOEI7TUFBQSxTQUN4RDtNQUFBLHdFQUFLO2FBQUEseUJBQTJCOzs7UUFEekI7UUFBQTtRQUFtQjtRQUFBO1FBQ3JCO1FBQUE7Ozs7b0JDREw7TUFBQTthQUFBOzs7OyJ9
